- src/packets.rs
I've encountered an issue where mysql_async wasn't able to establish SSL connection with a database, because the name of auth plugin was parsed incorrectly (`UnknownAuthPlugin { name: "mysql_native_password\u{0}" }`). The problem here is that the handshake packet contains two leading zero bytes instead of only one or none. This is the server I've been using: https://github.com/facebook/mysql-5.6 but I am unable to provide detailed configuration for that server nor a repro in a more popular mysql server version.
I've noticed that the https://github.com/mysql/mysql-proxy as well as https://github.com/mysql/mysql-server parses the handshake auth plugin part a bit differently - [the latter](https://github.com/mysql/mysql-server/blob/124c7ab1d6f914637521fd4463a993aa73403513/sql/auth/sql_authent …
> handshake packet to parse auth plugin name up to first zero byte

- src/io.rs
- src/packets.rs
- src/value/convert/bigdecimal.rs
- src/value/convert/mod.rs
- src/value/mod.rs
Casting between f32 and f64 can cause precision loss. I have a minimal reproduction here [in this repo](https://github.com/tomhoule/mysql-async-float-precision-loss-repro). This happens for us when writing and reading from `float4` columns. I haven't been able to find the proper place to test this, so there are no tests, but I manually confirmed that this fixes the issue in our case.
The naming of the variants is just an idea, I chose what rust users are probably most familiar with.
This is a breaking change, but I think it's pretty important to fix.
> Split Value::Float into 32 and 64 bit variants

- Cargo.toml
- README.md
- src/value/convert/mod.rs
Some upgrade notes:
- Replaced `time` 0.1's `impl ConvIr<Timespec> for ParseIr<Timespec>` and `impl From<Timespec> for Value` with `time` 0.2 related structs:
- `impl ConvIr<OffsetDateTime> for ParseIr<OffsetDateTime>` / `impl From<OffsetDateTime> for Value`
- `impl ConvIr<PrimitiveDateTime> for ParseIr<PrimitiveDateTime>` / `impl From<PrimitiveDateTime> for Value`
- `impl ConvIr<Date> for ParseIr<Date>` / `impl From<Date> for Value`
- `impl ConvIr<Time> for ParseIr<Time>` / `impl From<Time> for Value`
- Updated `impl From<time::Duration> for Value` to use `time::Duration`'s new `whole_x` functions.
- `time`'s `Time::parse` will reject any time outside of the 00:00:00-23:59:59 range, whereas MySQL's `TIME` data type works as both time and duration, allowing for -838:59:59 - 838:59:59. As …
> Upgrade `time` to 0.2

- Cargo.toml
- src/proto/codec/error.rs
The `failure` crate is officially deprecated/unmaintained (see https://rustsec.org/advisories/RUSTSEC-2020-0036.html). This replaces its only use with a manual implementation of the `std::error::Error` trait where necessary.
> Remove dependency on deprecated `failure` crate

- Cargo.toml
- src/params.rs
twox-hash hasn't been keeping up with the dependency update cycle, and
so brings in an old version of the rand crate. I didn't see a compelling
reason to use XxHash over the default hash algorithm, so just remove it.
> Drop dependency on twox-hash

- src/packets/mod.rs
rust-mysql-simple uses `nonce` to retrieve the nonce from a HandshakeResponse. Update nonce to be trimmed here so that
rust-mysql-simple can be updated to 0.28.
> Trim zero terminator from nonce.

- Cargo.toml
Updates regex to `1.5.5` as per [security advisory](https://blog.rust-lang.org/2022/03/08/cve-2022-24713.html)
> Update regex to `1.5.5`

- src/lib.rs
- src/named_params.rs
- src/params.rs
As discussed in blackbeam/mysql_async#194, MySQL actually accepts
arbitrary byte slices, not just strings, as queries. This commit is the
first in a cross-repo, likely ongoing effort to update both mysql_common
and mysql_async to accept *either* byte slices or strings - that
distinction is planned on the mysql_async side, but for now this updates
the main entrypoint for queries in this crate, which is
`pares_named_params`, to take `&[u8]` instead of `&str`.
This PR is intended to go along with a similar PR in `mysql_async` to update it
to work with these new APIs
> Make named parameter parsing use byte slices

- Cargo.toml
The RustCrypto project recently got control of the crate name `sha1`. This
commit switches over to the new name; the old `sha-1` name is now deprecated.
Details: https://github.com/RustCrypto/hashes/pull/350
> Switch from `sha-1` to `sha1`

- .github/workflows/rust.yml
- Cargo.toml
- src/packets/mod.rs
Signed-off-by: lance6716 <lance6716@gmail.com>
It's a lot of parsing work to do before start a GTID-based binlog stream, so I implemented `FromStr` for `Sid`. ref https://dev.mysql.com/doc/refman/8.0/en/replication-gtids-concepts.html
And I just start coding in rust some days ago, feel free to comment on my code :smile: 
BTW, I have some questions:
1. Why this structure is called `Sid` rather than GTID or uuid_set as in doc?
2. Can I add more check to other building functions? In order to avoid "ERROR 1774 (HY000): Malformed GTID specification" we can find the error when build it
3. I hope I can also add a GTIDSet struct to directly parse `2174B383-5441-11E8-B90A-C80AA9429562:1-3, 24DA167-0C0C-11E8-8442-00059A3C7B00:1-19`. What's about naming of it?
> Add parsing from string for Sid(GTID)

- src/value/convert/chrono.rs
Upgrading from 0.29.2 to 0.30.1 caused compilation issues with getting a NaiveTime from a row, e.g.:
```
let val: Option<NaiveTime> =
row.get_opt(col_idx).expect("row value should exist")?;
```
errors with the following:
```
|
606 |                         row.get_opt(col_idx).expect("row value should exist")?;
|                             ^^^^^^^ the trait `mysql_async::prelude::FromValue` is not implemented for `NaiveTime`
|
= help: the following other types implement trait `mysql_async::prelude::FromValue`:
Cow<'static, [u8]>
Cow<'static, str>
Deserialized<T>
NaiveDate
NaiveDateTime
Vec<u8>
[u8; N]
bigdecimal::BigDecimal
and 24 others
= note: required for `std::option::Option<NaiveTime>` to implement `mysql_async::prelude::FromValue`
note: required by a bound in …
```
> Implement FromValue for chrono NaiveTime

- Cargo.toml
- src/misc/raw/flags.rs
- src/named_params.rs
> Properly handle `?` in comments when parsing named parameters

- src/crypto/rsa.rs
In an 32-bit addressing space environment, usize is 4 bytes, which is not large enough to perform `2^32 * HASH_LEN` thus will trigger a panic. This PR fixes this problem by converting all the numbers to u64 before doing the comparison.
> Fix mgf1 panic in 32bit env

- Cargo.toml
I tried adding a dependency on mysql_async to an existing project, and I'm getting an error
```
unresolved import `bitflags::Flags` no `Flags` in the root
```
coming from mysql_common-0.30.6/src/misc/raw/flags.rs
which I think is because mysql_common has a dependency on bitflags = ^2.0.0. My Cargo.lock file is choosing version 2.2.1 (because i was already using it for something else).
However, mysql_common requires the `Flags` trait which was added in 2.3.0. If I am understanding the package management correctly, mysql_common should depend on the version of bitflags that contains all features it uses.
> Bump bitflags dependency

- Cargo.toml
- src/misc/mod.rs
- src/packets/mod.rs
- src/value/convert/mod.rs
This switches integer parsing from `lexical` to `btoi` crate.
This necessitated rewriting the version parsing function, which is now more robust - it correctly rejects some inputs that made the previous implementation panic.
[`lexical` sometimes returns incorrect results instead of an error](https://github.com/Alexhuszagh/rust-lexical/issues/105) when the input is too large for the provided type. This is the primary motivation for this change.
`lexical` also has [soundness issues](https://rustsec.org/advisories/RUSTSEC-2023-0055.html) and appears to be unmaintained. By contrast `btoi` is 100% safe code so it will never have these kinds of issues.
I kept `lexical` around for parsing floats because the standard library does not expose an API to convert from `&[u8]` to floats without going …
> Use a more correct crate for int parsing

- src/packets/caching_sha2_password.rs
- src/packets/mod.rs
We were trying to parse packets associated with public key requests/responses when using`caching_sha2_password` authentication. However, we don't believe that these packet types exist yet.
Allow packet parsing of public key requests and responses for `caching_sha2_password` authentication.
1. Create a new module to house details specific to `caching_sha2_password` authentication. We have a subsequent addition that is also `caching_sha2_password`-specific.
2. Introduce a packet to represent a public-key request for `caching_sha2_password`. Note that while this is similar to the one used for `sha256_password`, it has a different packet identifier.
3. Introduce a packet to represent a public-key response. This is shared between both `caching_sha2_password` and `sha256_password`, so it is …
> Add packets for `caching_sha2_password` public key retrieval

- src/packets/mod.rs
According to the [MySQL connection phase documentation](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase.html):
> In case the server sent a ERR packet as first packet it will happen before the client and server negotiated any capabilities. Therefore the ERR packet will not contain the SQL-state.
When using the `ServerError` type, we've run into a couple of issues:
1. When a server error that does not contain a SQLSTATE is deserialized, `ServerError` is populated with an `HY000` SQLSTATE code. This means, when calling `sql_state_str()` or reserializing, that an unexpected value is returned/included.
2. When creating a new server error, a SQLSTATE is required.
Allow the `ServerError` struct to represent cases where there an error is returned from the server …
> Make SQLSTATE optional in ServerError

- src/packets/mod.rs
Closes https://github.com/blackbeam/rust_mysql_common/issues/124
Credits to https://github.com/Weakky for this, I thought I could me it a PR to make it easier to be fixed.
Here is the explanation from https://regex101.com/ - the MariaDB version hack `5.5.5-` is now optional and a non capturing group.
> fix: update MariaDB version regex to make the version hack optional

- src/binlog/events/delete_rows_event.rs
- src/binlog/events/delete_rows_event_v1.rs
- src/binlog/events/mod.rs
- src/binlog/events/partial_update_rows_event.rs
- src/binlog/events/rows_event.rs
- src/binlog/events/update_rows_event.rs
- src/binlog/events/update_rows_event_v1.rs
- src/binlog/events/write_rows_event.rs
- src/binlog/events/write_rows_event_v1.rs
In our use-case at Materialize we are looking to gain access to the underlying flags attached to `RowsEvent`s to determine whether they represent the final event for a given statement/transaction.
Thanks!
> Expose a flags() method on RowsEventData to read corresponding event flags

- src/value/convert/mod.rs
fixes #133 
the mysql specification at https://github.com/blackbeam/rust_mysql_common/issues/url states that all TinyInt values between -128 and 127 are valid as the boolean value true (with the exclusion of 0 being false).
other clients have implemented the full range of their respective integer classes (e.g jdbc's Integer) conversions into boolean.
this commit adds that simple logic with either Value::Int(0) and Value::Uint(0) being false and all other Value::Int's and Value::UInt's being true.
proptests for both ranges were also added for sanity/regressions sake.
> added: parse integers to bool

- derive/Cargo.toml
- derive/src/error.rs
- derive/src/from_row/structs/mod.rs
- derive/src/from_value/enums/mod.rs
- derive/src/from_value/structs/mod.rs
- derive/src/lib.rs
Running cargo-deny reveals that the former is unmaintained (no releases for four years).  The latter is a drop-in replacement.
> Replace proc-macro-error crate with proc-macro-error2

- Cargo.toml
- derive/src/from_value/enums/mod.rs
- src/misc/raw/mod.rs
- src/packets/mod.rs
- src/row/convert/frunk.rs
This also implements x5 reduction of a `Column` structure size by moving names into a separate structure under an `Arc`.
> Remove `HlistFromRow` helper trait.

- Cargo.toml
- src/crypto/mod.rs
- src/crypto/rsa.rs
rand 0.9 split out fallible operations from Rng to TryRng
OsRng in rand 0.9 only implements the fallible trait
rand is not meant to be used for crypto, which is the case here
I've made an initial take where we replace Rng with our own trait that wraps getrandom. This allows test to continue using deterministic test case
Maybe these methods should return the error from `fill` rather than panic. But figured I'd keep this change conservative
> replace rand with getrandom

- Cargo.toml
- src/packets/mod.rs
- src/scramble.rs
I have tried my best at implementing a fix for issue #138 by following the given reference implementation as well as the RFC at https://www.rfc-editor.org/rfc/rfc8032#section-5.1.5. 
I have aligned my code as best as I can to the references given above and I have tested this locally using a modified `mysql_async`. However **I am no expert on cryptography** and cannot in good conscience take responsibility for the cryptographic correctness, as I am relying on low-level elliptic curve computations. 
If anyone could provide feedback and test data, I would very much appreciate it.
If this is accepted, I have already prepared the necessary changes to https://github.com/blackbeam/mysql_async/ as well. Should I open a separate pull request already, or wait?
Best regards!
> Added implementation of client_ed25519 authentification method

- Cargo.toml
`zstd` is only used by `binlog`, so I've gated it to avoid having to waste time building it.
> build(deps): gate `zstd` behind `binlog` feature

- Cargo.toml
Same as #165 but for dependencies required for `build_test_libs.rs`
> build(deps): gate `cc`, `cmake` and `subprocess` behind `test` feature
